import "./globals.css";
import { Metadata } from "next";
import { ReactNode } from "react";
import { Open_Sans } from "next/font/google";
import NavBar from "./components/NavBar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Knowsy!",
	description: "Generated by create next app",
};

function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className={openSans.className + " " + "max-w-6xl mx-auto relative"}>
				<NavBar />
				{children}
			</body>
		</html>
	);
}

export default RootLayout;
