import { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ReactNode } from "react";
import Footer from "../components/layout/Footer";
import NavBar from "../components/layout/Header";
import "./globals.css";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Knowsy!",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className + " " + "max-w-6xl mx-auto relative"}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
